name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout seedsigner-os
        uses: actions/checkout@v3
        with:
          repository: "LumenSigner/seedsigner-os"
          submodules: true
          path: "seedsigner-os"

      - name: checkout source
        uses: actions/checkout@v3
        with:
          path: "seedsigner-os/opt/rootfs-overlay/opt"

      - name: build
        run: |
          cd seedsigner-os/opt
          ./build.sh --pi0 --skip-repo

      - name: show sha256sum
        run: |
          cd seedsigner-os/images
          sha256sum *.img

      - name: upload images
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: "seedsigner-os/images/*.img"